using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class TheMadLad : MonoBehaviour {

    Rigidbody2D rb;

    float dirX, moveSpeed = 5f;
    
    bool facingRight = false;
    Vector3 localScale;

    Animator anim;


    // Use this for initialization
    void Start () {
        localScale = transform.localScale;
        rb = GetComponent<Rigidbody2D>();
        anim = GetComponent<Animator>();
	}
	
	// Update is called once per frame
	void Update () {
        dirX = Input.GetAxisRaw("Horizontal") * moveSpeed;

        if (rb.velocity.x != 0)
            anim.SetBool("isWalking", true);
        else
            anim.SetBool("isWalking", false);
    }

    private void FixedUpdate()
    {
        rb.velocity = new Vector2(dirX, rb.velocity.y);
    }

    private void LateUpdate()
    {
        if (dirX > 0)
            facingRight = true;
        else if (dirX < 0)
            facingRight = false;

        if (((facingRight) && (localScale.x < 0)) || ((!facingRight) && (localScale.x > 0)))
            localScale.x *= -1;

        transform.localScale = localScale;
    }
}
